Bauman_Consulting/urls.py
from django.urls import path
from .views import index
from .views import (
    page_Unser_Angebot,
    page_Kontakt,
    page_Organisatorisches_Sicherheitskonzept,
    page_Technisches_Sicherheitskonzept,
    page_Literatur,
    page_Bestellen,
    contact_form_view,
    kaufen_form_view,
)

app_name = 'Bauman_Consulting'

urlpatterns = [
    path('',index, name='index'),
    path("Unser_Angebot/", page_Unser_Angebot, name="Unser_Angebot"),
    path("Literatur/", page_Literatur, name="Literatur"),
    path("Kontakt/", page_Kontakt, name="Kontakt"),
    path("Bestellen/", page_Bestellen, name="Bestellen"),
    path("contact/", contact_form_view, name="contact_form"),
    path("kaufen/", kaufen_form_view, name="kaufen_form"),
    path("Organisatorisches_Sicherheitskonzept/",
        page_Organisatorisches_Sicherheitskonzept,
        name="Organisatorisches_Sicherheitskonzept",
    ),
    path(
        "Technisches_Sicherheitskonzept/",
        page_Technisches_Sicherheitskonzept,
        name="Technisches_Sicherheitskonzept",
    ),
    
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Bauman_Consulting.urls")),
]

Bauman_Consulting/models.py
from django.db import models


class ContactForm(models.Model):
    thema = models.CharField(max_length=100)
    vorname = models.CharField(max_length=100)
    nachname = models.CharField(max_length=100)
    firma = models.CharField(max_length=100)
    telephone = models.CharField(max_length=20)
    email = models.EmailField()
    betreff = models.CharField(max_length=100)
    nachricht = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class KaufenForm(models.Model):
    vorname = models.CharField(max_length=100, blank=True)
    nachname = models.CharField(max_length=100, blank=True)
    firma = models.CharField(max_length=100, blank=True)
    telephone = models.CharField(max_length=20, blank=True)
    email = models.EmailField(blank=True)
    betreff = models.CharField(max_length=100, blank=True)
    strasse = models.CharField(max_length=100, blank=True)
    hausnummer = models.CharField(max_length=100, blank=True)
    plz = models.CharField(max_length=100, blank=True)
    ort = models.CharField(max_length=100, blank=True)
    land = models.CharField(max_length=100, blank=True)
    nachricht = models.TextField(blank=True)
    vorname_l = models.CharField(max_length=100, blank=True)
    nachname_l = models.CharField(max_length=100, blank=True)
    firma_l = models.CharField(max_length=100, blank=True)
    telephone_l = models.CharField(max_length=20, blank=True)
    email_l = models.EmailField(blank=True)
    betreff_l = models.CharField(max_length=100, blank=True)
    strasse_l = models.CharField(max_length=100, blank=True)
    hausnummer_l = models.CharField(max_length=100, blank=True)
    plz_l = models.CharField(max_length=100, blank=True)
    ort_l = models.CharField(max_length=100, blank=True)
    land_l = models.CharField(max_length=100, blank=True)
    nachricht_l = models.TextField(blank=True)

Bauman_Consulting/forms.py
from django import forms
from .models import ContactForm, KaufenForm


class ContactFormForm(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = "__all__"


class KaufenFormForm(forms.ModelForm):
    class Meta:
        model = KaufenForm
        fields = "__all__"

Bauman_Consulting/views.py
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from django.http import FileResponse
import os
from django.conf import settings  # добавьте этот импорт
from .forms import ContactFormForm, KaufenFormForm
from django.core.mail import send_mail
 
 
import io
 
from django.db.models import Count
from datetime import datetime

# Create your views here.

def index(request):
    return render(request, 'Home.html' )

def page_Unterstutzung(request):
    return render(request, "utils/buttons/Unterstutzung.html")


def page_Referenzen(request):
    return render(request, "utils/buttons/Referenzen.html")


def page_Literatur(request):
    return render(request, "utils/buttons/Literatur.html")


def page_Kontakt(request):
    return render(request, "utils/buttons/Kontakt.html")


def page_Unser_Angebot(request):
    return render(request, "utils/buttons/Unser_Angebot.html")


def page_Bestellen(request):
    return render(request, "utils/buttons/Bestellen.html")


def page_Organisatorisches_Sicherheitskonzept(request):
    return render(request, "utils/buttons/Organisatorisches_Sicherheitskonzept.html")


def page_Technisches_Sicherheitskonzept(request):
    return render(request, "utils/buttons/Technisches_Sicherheitskonzept.html")

def contact_form_view(request):
    if request.method == "POST":
        form = ContactFormForm(request.POST)
        if form.is_valid():
            # form.save()  # Закомментируйте эту строку, чтобы не сохранять данные в базу

            # Отправка email peter.baumann.sulz@bluewin.ch
            subject = "New contact form submission"
            message = f"""
            Thema: {form.cleaned_data['thema']}
            Vorname: {form.cleaned_data['vorname']}
            Nachname: {form.cleaned_data['nachname']}
            Firma: {form.cleaned_data['firma']}
            Telephone: {form.cleaned_data['telephone']}
            E-mail: {form.cleaned_data['email']}
            Betreff: {form.cleaned_data['betreff']}
            Nachricht: {form.cleaned_data['nachricht']}
            """
            recipient_list = ["peter.baumann.sulz@bluewin.ch"]

            send_mail(subject, message, "sender@example.com", recipient_list)

            return render(request, 'Home.html' )  
    else:
        form = ContactFormForm()
    return render(request, "contact_form.html", {"form": form})

def kaufen_form_view(request):
    if request.method == "POST":
        form = KaufenFormForm(request.POST)
        if form.is_valid():
            #form.save()
            # Отправка email
            subject = "New contact form submission"
            message = f"""
            ---------------Rechnungsadresse---------------
            Vorname: {form.cleaned_data['vorname']}
            Nachname: {form.cleaned_data['nachname']}
            Firma: {form.cleaned_data['firma']}
            Telephone: {form.cleaned_data['telephone']}
            E-mail: {form.cleaned_data['email']}
            Betreff: {form.cleaned_data['betreff']}
            Strasse: {form.cleaned_data['strasse']}
            Hausnummer: {form.cleaned_data['hausnummer']} 
            PLZ: {form.cleaned_data['plz']}
            Ort: {form.cleaned_data['ort']}
            Land: {form.cleaned_data['land']} 
            Nachricht: {form.cleaned_data['nachricht']}
            ---------------Lieferadresse------------------
            Vorname: {form.cleaned_data['vorname_l']}
            Nachname: {form.cleaned_data['nachname_l']}
            Firma: {form.cleaned_data['firma_l']}
            Telephone: {form.cleaned_data['telephone_l']}
            E-mail: {form.cleaned_data['email_l']}
            Betreff: {form.cleaned_data['betreff_l']}
            Strasse: {form.cleaned_data['strasse_l']}
            Hausnummer: {form.cleaned_data['hausnummer_l']} 
            PLZ: {form.cleaned_data['plz_l']}
            Ort: {form.cleaned_data['ort_l']}
            Land: {form.cleaned_data['land_l']}
            Nachricht: {form.cleaned_data['nachricht_l']}
            """
            recipient_list = ["peter.baumann.sulz@bluewin.ch"]  # Замените на ваш email адрес

            send_mail(subject, message, "sender@example.com", recipient_list)

            print("Форма сохранена успешно")
            return render(request, 'Home.html' )
        else:
            print("Форма недействительна", form.errors)
    else:
        form = KaufenFormForm()
    return render(request, "utils/buttons/Bestellen.html", {"form": form})

Bauman_Consulting/templates/Home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{% static 'css/my_style.css' %}" rel="stylesheet">
    <title>Baumann_Consulting</title>
    <style>
        html, body {
            height: 100%;
            margin: 0;
        }
        .wrapper {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        .header, .footer {
            flex: 0 0 15%;
        }
        .content {
            flex: 1;
            overflow-y: auto;
        }
        .background_color {
            background-color: #f8f9fa; /* Цвет фона */
        }
        .border_background_color {
            border: 1px solid #dee2e6; /* Цвет рамки */
        }
    </style>
</head>

  <body>
 
        <nav class="navbar navbar-expand-lg navbar-light bg-light p-0 m-1 mr-1 header">

            
            <div class=" col-6  ">
                <img src="{% static 'images/L1.3.jpg' %}"  >
            </div>
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="col-6  justify-content-end collapse navbar-collapse p-0 m-0" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <div class="btn-group" role="group" aria-label="Large button group">
              
                        <a href="{% url 'Bauman_Consulting:index' %}" 
                        class="btn btn-outline-dark btn-no-border {% if request.path == '/' %}active{% endif %} "><b>Home</b></a>
        
                        <div class="dropdown" onmouseover="showDropdown()" onmouseout="hideDropdown()">
                            <a class="btn btn-outline-dark btn-no-border dropdown-toggle 
                            {% if request.path == '/Unser_Angebot/' %}active{% endif %}
                            {% if request.path == '/Technisches_Sicherheitskonzept/' %}active{% endif %}
                            {% if request.path == '/Organisatorisches_Sicherheitskonzept/' %}active{% endif %}" 
                            href="{% url 'Bauman_Consulting:Unser_Angebot' %}"  
                            id="unserAngebotDropdown" 
                            role="button">

                            <b><span class="unser-angebot-full">Unser Angebot</span><span 
                                    class="unser-angebot-short">Angebot</span></b>
                            </a>
        
                            <div class="dropdown-menu" 
                                 aria-labelledby="unserAngebotDropdown" 
                                 id="dropdownMenu">
                                 
                                <a class="dropdown-item {% if request.path == '/Technisches_Sicherheitskonzept/' %}active{% endif %}" 
                                    href="{% url 'Bauman_Consulting:Technisches_Sicherheitskonzept' %}">
                                    <span class="unser-angebot-full">Technisches Sicherheitskonzept</span><span class="unser-angebot-short">Tech. Sicherheit</span>
                                </a>
                                <a class="dropdown-item {% if request.path == '/Organisatorisches_Sicherheitskonzept/' %}active{% endif %} " 
                                    href="{% url 'Bauman_Consulting:Organisatorisches_Sicherheitskonzept' %}">
                                    <span class="unser-angebot-full">Organisatorisches Sicherheitskonzept</span><span class="unser-angebot-short">Org. Sicherheit</span>
                                </a>
                            </div>
                        </div>
        
                        <a href="{% url 'Bauman_Consulting:Literatur' %}" 
                        class="btn btn-outline-dark btn-no-border btn-mobile-small {% if request.path == '/Literatur/' %}active{% endif %}"><b>Literatur</b></a>
        
                        <a href="{% url 'Bauman_Consulting:Kontakt' %}" 
                        class="btn btn-outline-dark btn-no-border btn-mobile-small {% if request.path == '/Kontakt/' %}active{% endif %}"><b>Kontakt</b></a>
                    </div>
                </ul>
            </div>
        </nav>
    
        

        <div class="content background_color" style="display: flex; flex-direction: column; min-height: 100vh;">
            {% block content %}
            <div class="container-fluid background_color border_background_color">
                <div class="row m-2 container-fluid">
                    <div class="col-12 col-lg-8 text-center"> </div>
                </div>
                <div class="row m-2 container-fluid">
                    <div class="col-12 ">
                        <div class="text-center">
                            <h1>
                                <br/>
                                <b>Leben in Sicherheit geht uns alle an…</b>
                            </h1>
                        </div>
                        
                        <div class="image-container m-2 p-0">
                            <img src="{% static 'images/kkl2.1.jpg' %}" alt="Description of image" class="responsive-image">
                        </div>
                        
                        <div class="container">
                            <div class="row p-0">  
                                <div class="col-12 col-md-6 p-0"> 
                                    <b class="h5">Kontakt</b> <br/>
                                    <b>Baumann Consulting</b> <span class="col-4 footer-link link-light">
                                        <a href="https://www.linkedin.com/in/peter-baumann-011b1358/">LinkedIn</a>
                                    </span> <br/>
                                    Dr. Peter Baumann  <br/>
                                    Steinliacherstrasse 22 / 5085 Sulz (AG)<br/>  
                                    
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                                        <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.6 17.6 0 0 0 4.168 6.608 17.6 17.6 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.68.68 0 0 0-.58-.122l-2.19.547a1.75 1.75 0 0 1-1.657-.459L5.482 8.062a1.75 1.75 0 0 1-.46-1.657l.548-2.19a.68.68 0 0 0-.122-.58zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.68.68 0 0 0 .178.643l2.457 2.457a.68.68 0 0 0 .644.178l2.189-.547a1.75 1.75 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.6 18.6 0 0 1-7.01-4.42 18.6 18.6 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877z" />
                                    </svg>
                                    +41 79 359 2116 / Schweiz <br/>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1zm13 2.383-4.708 2.825L15 11.105zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741M1 11.105l4.708-2.897L1 5.383z" />
                                    </svg>
                                    Peter.Baumann.Sulz@bluewin.ch <br/>
                                </div> 
                                
                                <div class="col-12 col-md-6 p-0"> 
                                    <b class="h5">Unternehmensprofil</b> <br/> 
                                    Baumann Consulting unterstützt die Entwicklung einer sicherheitsorientierten technischen Auslegung von Strukturen, Systemen und Komponenten im Kraftwerksbereich und die dafür erforderliche sicherheitsorientierte Entwicklung von Mensch & Organisation durch Mitarbeit in Projekten und Schulung der Mitarbeiter
                                </div> 
                            </div>     
                        </div>
                        
                    </div>
                {% endblock %}
            </div>
        
            
        </div>
    






















    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Bauman_Consulting/templates/utils/Logo/logo.html
<div class="row p-0 m-0">
    <div class="col-6 col-lg-2 p-0 m-0">
        <div class="row">
            <div class="stripe orange" style="width: 70%; margin-bottom: 5px;"></div>
        </div>
        <div class="row">
            <div class="stripe black" style="width: 70%; margin-bottom: 5px;"></div>
        </div>
        <div class="row">
            <div class="stripe black" style="width: 70%; "></div>
        </div>
    </div>
    <div class="col-6  col-lg-6 p-0  m-0">
        <div class="row">
            <b class="big_bc_orange">BC</b>
        </div>
        <div class="row">
            <b style="font-size: 12px;">BAUMANN CONSALTING</b>
        </div>
    </div>
</div>

Bauman_Consulting/templates/utils/Personal_Area/Personal_Area.html
{% extends 'Home.html' %}

{% block content %}
{% load static %}
    <div class="container-fluid background_color border_background_color">
        <div class="divstyle">
            <div class="row m-1 container-fluid">
                <div class="col-12 col-lg-12 m-2  text-center" style="border-bottom: 1px solid black;">
                    <h1><b>Baumann Consulting</b></h1>
                </div>
                <h1>Contacts</h1>
                <h1>Total contacts: <b>{{ contacts_count }}</b></h1> <!-- Отображаем статистику -->
                <img src="{% url 'plot_contacts_statistics' %}" alt="Contacts Plot" width="400" height="300">
                <ul>
                    {% for contact in contacts %}
                        <li>
                            Thema: {{ contact.thema }}<br>
                            Vorname: <b>{{ contact.vorname }}</b><br>
                            Nachname: <b>{{ contact.nachname }}</b><br>
                            Firma: {{ contact.firma }}<br>
                            Telephone: {{ contact.telephone }}<br>
                            Email: {{ contact.email }}<br>
                            Betreff: {{ contact.betreff }}<br>
                            Nachricht: {{ contact.nachricht }}<br>
                        </li><br>
                    {% endfor %}
                </ul>
            </div> 
            <!-- Вставляем изображение графика -->
            

        </div>
    </div>
{% endblock %}

Bauman_Consulting/templates/utils/buttons/Bestellen.html
{% extends 'Home.html' %}

{% block content %}
{% load static %}
<div class="container-fluid background_color border_background_color">
    <div class="divstyle">
        <div class="row m-1 container-fluid">
            <div class="col-12 col-lg-12 m-2 text-center" style="border-bottom: 1px solid black;">
                <h1><b>Baumann Consulting</b></h1><br/>
            </div>
            
            <div class="col-12 col-lg-4">
                <h2>
                    <h1>Buchbestellung:</h1>
                    <br><br>
                    <b>Preise:</b> <br>
                    Band 1: <br>
                    Leitfaden zum Aufbau eines
                    betrieblichen Sicherheitsmanagements <br><br>
                    <b>50.00 CHF/Stück</b> (inkl. MwSt. und Versandt innerhalb der Schweiz)
                    <br><br>
                    Band 2:
                    <br>
                    Betriebliches Sicherheitsmanagement für
                    Kernkraftwerke mit Leichtwasserreaktoren
                    In der Schweiz<br><br>
                    <b>75.00 CHF/Stück</b>  (inkl. MwSt. und Versandt innerhalb der Schweiz)
                    <br><br>
                    Nach erfolgter Bestellung erhalten Sie per E-Mail eine
                    Rechnung und Einzahlungsschein mit QR-Code. Nach erfolgter Bezahlung erfolgt die Lieferung innerhalb von max. 3 Wochen. <br>
                    Bei Lieferungen ausserhalb der Schweiz ist der Rechnungsbetrag abhängig vom Land und der zu liefernden Menge.

                </h2>
            </div>
            <div class="col-12 col-lg-4">
                    <b>
                         <form action="{% url 'Bauman_Consulting:kaufen_form' %}" method="POST" class="  col-12">
                            {% csrf_token %}
                            <div class="row">
                                Rechnungsadresse
                            </div>
                        <div class=" custom_form2">    
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="vorname">Vorname:</label>
                                    <input type="text" id="vorname" name="vorname" required>
                                </div>
                                <div class="col-md-6">
                                    <label for="nachname">Nachname:</label>
                                    <input type="text" id="nachname" name="nachname" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="firma">Firma:</label>
                                    <input type="text" id="firma" name="firma" required>
                                </div>
                                <div class="col-md-6">
                                    <label for="telephone">Telefon:</label>
                                    <input type="text" id="telephone" name="telephone" required>
                                </div>
                            </div>
                            <label for="email">E-mail:</label>
                            <input type="email" id="email" name="email" required>
                            <label for="betreff">Betreff:</label>
                            <input type="text" id="betreff" name="betreff" required>
                            <div class="row">
                                <div class="col-md-8">
                                    <label for="strasse">Strasse:</label>
                                    <input type="text" id="strasse" name="strasse" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="hausnummer">Hausnummer:</label>
                                    <input type="text" id="hausnummer" name="hausnummer" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="plz">PLZ:</label>
                                    <input type="text" id="plz" name="plz" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="ort">Ort:</label>
                                    <input type="text" id="ort" name="ort" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="land">Land:</label>
                                    <input type="text" id="land" name="land" required>
                                </div>
                            </div>
                            <label for="nachricht">Bitte geben Sie die gewünschte Anzahl pro Band an:</label>
                            <textarea id="nachricht" name="nachricht" rows="4" required></textarea>
                            <button class="btn btn-primary btn-lg" type="button" onclick="copyFormData()">Lieferadresse gleich Rechnungsadresse</button>
                        </div>  
                    </b>
                 
            </div> 
            <div class="col-12 col-lg-4 ">
                    <b>
                            <div class="row">
                                Lieferadresse
                            </div>
                        <div class=" custom_form2">
                             
                            
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="vorname_l">Vorname:</label>
                                    <input type="text" id="vorname_l" name="vorname_l" required>
                                </div>
                                <div class="col-md-6">
                                    <label for="nachname_l">Nachname:</label>
                                    <input type="text" id="nachname_l" name="nachname_l" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="firma_l">Firma:</label>
                                    <input type="text" id="firma_l" name="firma_l" required>
                                </div>
                                <div class="col-md-6">
                                    <label for="telephone_l">Telefon:</label>
                                    <input type="text" id="telephone_l" name="telephone_l" required>
                                </div>
                            </div>
                            <label for="email_l">E-mail:</label>
                            <input type="email" id="email_l" name="email_l" required>
                            <label for="betreff_l">Betreff:</label>
                            <input type="text" id="betreff_l" name="betreff_l" required>
                            <div class="row">
                                <div class="col-md-8">
                                    <label for="strasse_l">Strasse:</label>
                                    <input type="text" id="strasse_l" name="strasse_l" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="hausnummer_l">Hausnummer:</label>
                                    <input type="text" id="hausnummer_l" name="hausnummer_l" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="plz_l">PLZ:</label>
                                    <input type="text" id="plz_l" name="plz_l" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="ort_l">Ort:</label>
                                    <input type="text" id="ort_l" name="ort_l" required>
                                </div>
                                <div class="col-md-4">
                                    <label for="land_l">Land:</label>
                                    <input type="text" id="land_l" name="land_l" required>
                                </div>
                            </div>
                            <label for="nachricht_l">Nachricht:</label>
                            <textarea id="nachricht_l" name="nachricht_l" rows="4" required></textarea>
                            <button class="btn btn-primary btn-lg" type="submit">Bestellen</button>
                        </div>
                    </b>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    // Функция для копирования данных из первой формы во вторую
    function copyFormData() {
        // Получаем значения из полей первой формы
        var vorname = document.getElementById('vorname').value;
        var nachname = document.getElementById('nachname').value;
        var firma = document.getElementById('firma').value;
        var telephone = document.getElementById('telephone').value;
        var email = document.getElementById('email').value;
        var strasse = document.getElementById('strasse').value;
        var hausnummer = document.getElementById('hausnummer').value;
        var plz = document.getElementById('plz').value;
        var ort = document.getElementById('ort').value;
        var land = document.getElementById('land').value; 
        var betreff = document.getElementById('betreff').value;
        var nachricht = document.getElementById('nachricht').value;

        // Заполняем поля второй формы данными из первой
        document.getElementById('vorname_l').value = vorname;
        document.getElementById('nachname_l').value = nachname;
        document.getElementById('firma_l').value = firma;
        document.getElementById('telephone_l').value = telephone;
        document.getElementById('email_l').value = email;
        document.getElementById('strasse_l').value = strasse;
        document.getElementById('hausnummer_l').value = hausnummer;
        document.getElementById('plz_l').value = plz;
        document.getElementById('ort_l').value = ort;
        document.getElementById('land_l').value = land;
        document.getElementById('betreff_l').value = betreff;
        //document.getElementById('nachricht_l').value = nachricht;
    }
</script>
{% endblock %}